config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers
  devise_for :admins
  devise_for :users
  root 'home#index'
  get 'home/about'

  post '/' => 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_3ee0242d059548e7bd3cfc8c9af1f467')
    if params[:ticker] == ''
      @nothing = "Hey! You Forgot to Enter a Symbol"
    elsif params[:ticker]
      begin
        @stocklogo=StockQuote::Stock.logo(params[:ticker])
        @stockcompany=StockQuote::Stock.company(params[:ticker])
      rescue RuntimeError
        @error = 'Hey! That Stock Symbol does not exist. Please try again'
      end
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
        <%= link_to 'Stocks', root_path, class: 'navbar-brand' %> |
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class: 'nav-link'  %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>
<p>Rails app</p>

app/views/home/index.html.erb
<h1>Stock Market App</h1>
<%@api%>

  <%= form_tag root_path, :method => 'POST' do%>
    <%= text_field_tag :ticker, nil, placeholder: 'Enter Ticker Symbol', size: 50 %>
    <%= submit_tag 'Search' %>
    <%end%>
</br>
<% if @stocklogo%>
<strong><%= @stockcompany.company_name%></strong>
</br> </br>
<img src="<%= @stocklogo.url%>"> 
</br> </br>
<%= @stockcompany.description%>
<% elsif @nothing%>
<%= @nothing%>
<% end %>

<%if @error %>
  <%= @error %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock App Sample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar'%>
    <div class='container'>
    </br>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
    <%= render 'home/footer'%>
  </body>
</html>